import type { Question } from "./types";

export const questions: Question[] = [
  {
    id: "variables-01",
    set: "easy",
    topic: "variables",
    difficulty: "easy",
    type: "multiple-choice",
    prompt: { en: "Which line correctly stores the value 12 in a variable named `age`?", fr: "Quelle ligne stocke correctement la valeur 12 dans une variable nommée `age` ?" },
    choices: ["age = 12", "12 = age", "age == 12", "let age = 12"],
    answer: "age = 12",
    explanation: { en: "Python assigns the value on the right to the variable name on the left with =.", fr: "Python affecte la valeur à droite au nom de variable à gauche avec =." },
  },
  {
    id: "variables-02",
    set: "medium",
    topic: "variables",
    difficulty: "medium",
    type: "output",
    prompt: { en: "What does this program print?", fr: "Qu'affiche ce programme ?" },
    codeSnippet: "score = 8\nbonus = 4\nscore = score + bonus\nprint(score)",
    acceptedAnswers: ["12"],
    explanation: { en: "score starts at 8. Adding the 4 bonus points changes it to 12.", fr: "score commence à 8. L'ajout des 4 points bonus le fait passer à 12." },
  },
  {
    id: "variables-03",
    set: "hard",
    topic: "variables",
    difficulty: "hard",
    type: "fill",
    prompt: { en: "Complete only the missing expression so `final_score` becomes 15: `score = 10; bonus = 5; final_score = ___`", fr: "Complétez seulement l'expression manquante pour que `final_score` vaille 15 : `score = 10; bonus = 5; final_score = ___`" },
    acceptedAnswers: ["score + bonus", "score+bonus", "10 + 5", "10+5"],
    explanation: { en: "Enter score + bonus. It adds 10 and 5, so final_score becomes 15.", fr: "Entrez score + bonus. Cela additionne 10 et 5, donc final_score vaut 15." },
  },
  {
    id: "variables-04",
    set: "mixed",
    topic: "variables",
    difficulty: "medium",
    type: "code",
    prompt: { en: "The variables `width` and `height` are provided. Store the rectangle area in `area`.", fr: "Les variables `width` et `height` sont fournies. Stockez l'aire du rectangle dans `area`." },
    starterCode: "# width and height are already provided\narea = 0",
    resultVariable: "area",
    tests: [
      { label: { en: "small rectangle", fr: "petit rectangle" }, inputs: { width: 3, height: 4 }, expected: 12 },
      { label: { en: "zero width", fr: "largeur nulle" }, inputs: { width: 0, height: 8 }, expected: 0 },
      { label: { en: "decimal values", fr: "valeurs décimales" }, inputs: { width: 2.5, height: 4 }, expected: 10 },
    ],
    explanation: { en: "Multiply the two provided variables: area = width * height.", fr: "Multipliez les deux variables fournies : area = width * height." },
  },
  {
    id: "types-01",
    set: "easy",
    topic: "types",
    difficulty: "easy",
    type: "multiple-choice",
    prompt: { en: "What is the type of `3.14` in Python?", fr: "Quel est le type de `3.14` en Python ?" },
    choices: ["int", "float", "str", "bool"],
    answer: "float",
    explanation: { en: "A number containing a decimal point is a float.", fr: "Un nombre contenant un point décimal est un float." },
  },
  {
    id: "types-02",
    set: "mixed",
    topic: "types",
    difficulty: "medium",
    type: "output",
    prompt: { en: "What does this program print?", fr: "Qu'affiche ce programme ?" },
    codeSnippet: "value = \"8\"\nprint(int(value) + 2)",
    acceptedAnswers: ["10"],
    explanation: { en: "int converts the string \"8\" to the integer 8, then 2 is added.", fr: "int convertit la chaîne \"8\" en entier 8, puis ajoute 2." },
  },
  {
    id: "types-03",
    set: "medium",
    topic: "types",
    difficulty: "medium",
    type: "fill",
    prompt: { en: "Which one word goes in the blank to turn `\"15\"` into an integer? `age = ___(\"15\")`", fr: "Quel mot faut-il écrire dans le blanc pour transformer `\"15\"` en entier ? `age = ___(\"15\")`" },
    acceptedAnswers: ["int"],
    explanation: { en: "int converts a numeric string into an integer.", fr: "int convertit une chaîne numérique en entier." },
  },
  {
    id: "types-04",
    set: "hard",
    topic: "types",
    difficulty: "hard",
    type: "code",
    prompt: { en: "`text_number` contains a whole number written as text. Convert it to an integer and store it in `number`.", fr: "`text_number` contient un nombre entier écrit comme texte. Convertissez-le en entier et stockez-le dans `number`." },
    starterCode: "# text_number is already provided\nnumber = 0",
    resultVariable: "number",
    tests: [
      { label: { en: "single digit", fr: "un chiffre" }, inputs: { text_number: "7" }, expected: 7 },
      { label: { en: "two digits", fr: "deux chiffres" }, inputs: { text_number: "25" }, expected: 25 },
      { label: { en: "zero", fr: "zéro" }, inputs: { text_number: "0" }, expected: 0 },
    ],
    explanation: { en: "Use number = int(text_number) to convert the text into an integer.", fr: "Utilisez number = int(text_number) pour convertir le texte en entier." },
  },
  {
    id: "conditions-01",
    set: "easy",
    topic: "conditions",
    difficulty: "easy",
    type: "multiple-choice",
    prompt: { en: "Which keyword checks another condition after `if`?", fr: "Quel mot-clé vérifie une autre condition après `if` ?" },
    choices: ["else if", "elif", "then", "case"],
    answer: "elif",
    explanation: { en: "Python uses elif for an additional condition.", fr: "Python utilise elif pour une condition supplémentaire." },
  },
  {
    id: "conditions-02",
    set: "mixed",
    topic: "conditions",
    difficulty: "medium",
    type: "output",
    prompt: { en: "What does this program print?", fr: "Qu'affiche ce programme ?" },
    codeSnippet: "score = 12\nif score >= 10:\n    print(\"pass\")\nelse:\n    print(\"retry\")",
    acceptedAnswers: ["pass"],
    explanation: { en: "12 is greater than or equal to 10, so the if branch runs.", fr: "12 est supérieur ou égal à 10, donc le bloc if s'exécute." },
  },
  {
    id: "conditions-03",
    set: "hard",
    topic: "conditions",
    difficulty: "hard",
    type: "fill",
    prompt: { en: "Complete only the missing word so both conditions must be true: `if age >= 10 ___ age <= 13:`", fr: "Complétez seulement le mot manquant pour que les deux conditions soient vraies : `if age >= 10 ___ age <= 13:`" },
    acceptedAnswers: ["and"],
    explanation: { en: "Enter and because the age must satisfy both limits: at least 10 and at most 13.", fr: "Entrez and car l'âge doit respecter les deux limites : au moins 10 et au plus 13." },
  },
  {
    id: "conditions-04",
    set: "medium",
    topic: "conditions",
    difficulty: "medium",
    type: "code",
    prompt: { en: "The variable `number` is provided. Store `\"positive\"`, `\"negative\"`, or `\"zero\"` in `sign`.", fr: "La variable `number` est fournie. Stockez `\"positive\"`, `\"negative\"` ou `\"zero\"` dans `sign`." },
    starterCode: "# number is already provided\nsign = \"\"\n# Use if / elif / else",
    resultVariable: "sign",
    tests: [
      { label: { en: "positive number", fr: "nombre positif" }, inputs: { number: 9 }, expected: "positive" },
      { label: { en: "negative number", fr: "nombre négatif" }, inputs: { number: -2 }, expected: "negative" },
      { label: { en: "zero", fr: "zéro" }, inputs: { number: 0 }, expected: "zero" },
    ],
    explanation: { en: "Compare number with zero using if, elif, and else, assigning the matching text to sign.", fr: "Comparez number avec zéro avec if, elif et else, puis affectez le texte correspondant à sign." },
  },
  {
    id: "loops-01",
    set: "easy",
    topic: "loops",
    difficulty: "easy",
    type: "output",
    prompt: { en: "What does this program print on one line?", fr: "Qu'affiche ce programme sur une seule ligne ?" },
    codeSnippet: "for i in range(3):\n    print(i, end=\" \" )",
    acceptedAnswers: ["0 1 2", "0 1 2 "],
    explanation: { en: "range(3) produces 0, 1, and 2. The end argument keeps output on one line.", fr: "range(3) produit 0, 1 et 2. L'argument end garde l'affichage sur une ligne." },
  },
  {
    id: "loops-02",
    set: "medium",
    topic: "loops",
    difficulty: "medium",
    type: "multiple-choice",
    prompt: { en: "How many times does `for i in range(2, 8, 2)` run?", fr: "Combien de fois `for i in range(2, 8, 2)` s'exécute-t-elle ?" },
    choices: ["2", "3", "4", "6"],
    answer: "3",
    explanation: { en: "The produced values are 2, 4, and 6: three iterations.", fr: "Les valeurs produites sont 2, 4 et 6 : trois itérations." },
  },
  {
    id: "loops-03",
    set: "hard",
    topic: "loops",
    difficulty: "hard",
    type: "output",
    prompt: { en: "What final number does this program print?", fr: "Quel nombre final ce programme affiche-t-il ?" },
    codeSnippet: "count = 0\nfor number in [2, 7, 4, 9]:\n    if number > 5:\n        count = count + 1\nprint(count)",
    acceptedAnswers: ["2"],
    explanation: { en: "Only 7 and 9 are greater than 5, so count increases twice and ends at 2.", fr: "Seuls 7 et 9 sont supérieurs à 5, donc count augmente deux fois et termine à 2." },
  },
  {
    id: "loops-04",
    set: "mixed",
    topic: "loops",
    difficulty: "hard",
    type: "code",
    prompt: { en: "The list `values` is provided. Store the sum of its even numbers in `total`.", fr: "La liste `values` est fournie. Stockez la somme de ses nombres pairs dans `total`." },
    starterCode: "# values is already provided\ntotal = 0\n# Add a loop and a condition",
    resultVariable: "total",
    tests: [
      { label: { en: "mixed values", fr: "valeurs mixtes" }, inputs: { values: [1, 2, 3, 4] }, expected: 6 },
      { label: { en: "no even values", fr: "aucune valeur paire" }, inputs: { values: [1, 3, 5] }, expected: 0 },
      { label: { en: "negative values", fr: "valeurs négatives" }, inputs: { values: [-4, -1, 2] }, expected: -2 },
      { label: { en: "empty list", fr: "liste vide" }, inputs: { values: [] }, expected: 0 },
    ],
    explanation: { en: "Loop through values and add each number to total when number % 2 == 0.", fr: "Parcourez values et ajoutez chaque nombre à total lorsque number % 2 == 0." },
  },
  {
    id: "lists-01",
    set: "easy",
    topic: "lists",
    difficulty: "easy",
    type: "output",
    prompt: { en: "What does this program print?", fr: "Qu'affiche ce programme ?" },
    codeSnippet: "colors = [\"red\", \"blue\", \"green\"]\nprint(colors[1])",
    acceptedAnswers: ["blue"],
    explanation: { en: "List positions start at 0, so index 1 selects the second item: blue.", fr: "Les positions d'une liste commencent à 0, donc l'indice 1 sélectionne le deuxième élément : blue." },
  },
  {
    id: "lists-02",
    set: "medium",
    topic: "lists",
    difficulty: "medium",
    type: "multiple-choice",
    prompt: { en: "Which method adds one item to the end of a list?", fr: "Quelle méthode ajoute un élément à la fin d'une liste ?" },
    choices: ["add", "push", "append", "insert_end"],
    answer: "append",
    explanation: { en: "list.append(value) adds value to the end of the list.", fr: "list.append(value) ajoute value à la fin de la liste." },
  },
  {
    id: "lists-03",
    set: "mixed",
    topic: "lists",
    difficulty: "medium",
    type: "fill",
    prompt: { en: "What goes inside `values[___]` to select the first three items? Enter only the missing slice.", fr: "Que faut-il écrire dans `values[___]` pour sélectionner les trois premiers éléments ? Entrez seulement la tranche manquante." },
    acceptedAnswers: [":3", "0:3"],
    explanation: { en: "Enter :3 (or 0:3). A slice stops before 3, so it selects positions 0, 1, and 2.", fr: "Entrez :3 (ou 0:3). Une tranche s'arrête avant 3, donc elle sélectionne les positions 0, 1 et 2." },
  },
  {
    id: "lists-04",
    set: "hard",
    topic: "lists",
    difficulty: "hard",
    type: "code",
    prompt: { en: "The list `values` is provided. Build `doubled_values` containing each number multiplied by 2.", fr: "La liste `values` est fournie. Construisez `doubled_values` avec chaque nombre multiplié par 2." },
    starterCode: "# values is already provided\ndoubled_values = []\n# Use a loop and append",
    resultVariable: "doubled_values",
    tests: [
      { label: { en: "small numbers", fr: "petits nombres" }, inputs: { values: [1, 2, 3] }, expected: [2, 4, 6] },
      { label: { en: "includes zero", fr: "avec zéro" }, inputs: { values: [0, 5] }, expected: [0, 10] },
      { label: { en: "one number", fr: "un nombre" }, inputs: { values: [7] }, expected: [14] },
      { label: { en: "empty list", fr: "liste vide" }, inputs: { values: [] }, expected: [] },
    ],
    explanation: { en: "Loop through values and append number * 2 to doubled_values each time.", fr: "Parcourez values et ajoutez number * 2 à doubled_values à chaque tour." },
  },
  {
    id: "variables-05",
    set: "easy",
    topic: "variables",
    difficulty: "easy",
    type: "multiple-choice",
    prompt: { en: "Which is a valid Python variable name?", fr: "Lequel est un nom de variable Python valide ?" },
    choices: ["student_score", "student-score", "2students", "student score"],
    answer: "student_score",
    explanation: { en: "Variable names may contain letters, numbers, and underscores, but cannot start with a number.", fr: "Les noms de variables peuvent contenir des lettres, des chiffres et des underscores, mais ne peuvent pas commencer par un chiffre." },
  },
  {
    id: "variables-06",
    set: "medium",
    topic: "variables",
    difficulty: "medium",
    type: "output",
    prompt: { en: "What does this program print?", fr: "Qu'affiche ce programme ?" },
    codeSnippet: "points = 5\npoints = points + 3\npoints = points * 2\nprint(points)",
    acceptedAnswers: ["16"],
    explanation: { en: "points becomes 8 after the addition, then 16 after the multiplication.", fr: "points devient 8 après l'addition, puis 16 après la multiplication." },
  },
  {
    id: "variables-07",
    set: "mixed",
    topic: "variables",
    difficulty: "medium",
    type: "output",
    prompt: { en: "What does this program print?", fr: "Qu'affiche ce programme ?" },
    codeSnippet: "x = 3\ny = x\nx = 9\nprint(y)",
    acceptedAnswers: ["3"],
    explanation: { en: "y receives the value 3. Changing x later does not change y.", fr: "y reçoit la valeur 3. Modifier x ensuite ne modifie pas y." },
  },
  {
    id: "variables-08",
    set: "hard",
    topic: "variables",
    difficulty: "hard",
    type: "output",
    prompt: { en: "A game starts with 3 lives. What does this program print?", fr: "Un jeu commence avec 3 vies. Qu'affiche ce programme ?" },
    codeSnippet: "lives = 3\nbonus_lives = 2\nlives = lives + bonus_lives\nbonus_lives = 0\nprint(lives)",
    acceptedAnswers: ["5"],
    explanation: { en: "The 2 bonus lives are added to the 3 lives, making 5. Changing bonus_lives later does not change lives.", fr: "Les 2 vies bonus sont ajoutées aux 3 vies, ce qui donne 5. Modifier bonus_lives ensuite ne change pas lives." },
  },
  {
    id: "types-05",
    set: "easy",
    topic: "types",
    difficulty: "easy",
    type: "multiple-choice",
    prompt: { en: "Which value is a boolean?", fr: "Quelle valeur est un booléen ?" },
    choices: ["True", "\"True\"", "1.0", "\"yes\""],
    answer: "True",
    explanation: { en: "True without quotation marks is a boolean. With quotes, it is text.", fr: "True sans guillemets est un booléen. Avec des guillemets, c'est du texte." },
  },
  {
    id: "types-06",
    set: "medium",
    topic: "types",
    difficulty: "medium",
    type: "output",
    prompt: { en: "What does this program print?", fr: "Qu'affiche ce programme ?" },
    codeSnippet: "word = \"go\"\nprint(word * 3)",
    acceptedAnswers: ["gogogo"],
    explanation: { en: "Multiplying a string by 3 repeats it three times.", fr: "Multiplier une chaîne par 3 la répète trois fois." },
  },
  {
    id: "types-07",
    set: "mixed",
    topic: "types",
    difficulty: "easy",
    type: "fill",
    prompt: { en: "Which one word goes in the blank to turn `\"12.5\"` into a decimal number? `price = ___(\"12.5\")`", fr: "Quel mot faut-il écrire dans le blanc pour transformer `\"12.5\"` en nombre décimal ? `price = ___(\"12.5\")`" },
    acceptedAnswers: ["float"],
    explanation: { en: "float converts decimal text such as \"12.5\" into a decimal number.", fr: "float convertit un texte décimal comme \"12.5\" en nombre décimal." },
  },
  {
    id: "types-08",
    set: "hard",
    topic: "types",
    difficulty: "hard",
    type: "multiple-choice",
    prompt: { en: "What is the type of the result of `9 / 3` in Python?", fr: "Quel est le type du résultat de `9 / 3` en Python ?" },
    choices: ["float", "int", "str", "bool"],
    answer: "float",
    explanation: { en: "The / operator produces a float, even when the mathematical result is a whole number.", fr: "L'opérateur / produit un float, même lorsque le résultat mathématique est un nombre entier." },
  },
  {
    id: "conditions-05",
    set: "easy",
    topic: "conditions",
    difficulty: "easy",
    type: "output",
    prompt: { en: "What does this program print?", fr: "Qu'affiche ce programme ?" },
    codeSnippet: "age = 10\nif age < 13:\n    print(\"child\")\nelse:\n    print(\"teen\")",
    acceptedAnswers: ["child"],
    explanation: { en: "10 is less than 13, so the first branch runs.", fr: "10 est inférieur à 13, donc le premier bloc s'exécute." },
  },
  {
    id: "conditions-06",
    set: "medium",
    topic: "conditions",
    difficulty: "medium",
    type: "multiple-choice",
    prompt: { en: "Which condition is `True` only when `age` is between 12 and 18 inclusive?", fr: "Quelle condition est `True` seulement lorsque `age` est compris entre 12 et 18 inclus ?" },
    choices: ["age >= 12 and age <= 18", "age >= 12 or age <= 18", "age > 12 and age > 18", "age == 12 and age == 18"],
    answer: "age >= 12 and age <= 18",
    explanation: { en: "Both limits must be satisfied, so the conditions are joined with and.", fr: "Les deux limites doivent être respectées, donc les conditions sont reliées par and." },
  },
  {
    id: "conditions-07",
    set: "mixed",
    topic: "conditions",
    difficulty: "hard",
    type: "output",
    prompt: { en: "What does this program print?", fr: "Qu'affiche ce programme ?" },
    codeSnippet: "number = 8\nif number > 5:\n    if number < 10:\n        print(\"inside\")\n    else:\n        print(\"large\")\nelse:\n    print(\"small\")",
    acceptedAnswers: ["inside"],
    explanation: { en: "8 passes both nested conditions: it is above 5 and below 10.", fr: "8 satisfait les deux conditions imbriquées : il est supérieur à 5 et inférieur à 10." },
  },
  {
    id: "conditions-08",
    set: "hard",
    topic: "conditions",
    difficulty: "hard",
    type: "output",
    prompt: { en: "What does this program print?", fr: "Qu'affiche ce programme ?" },
    codeSnippet: "points = 7\nif points >= 10:\n    print(\"gold\")\nelif points >= 5:\n    print(\"silver\")\nelse:\n    print(\"bronze\")",
    acceptedAnswers: ["silver"],
    explanation: { en: "7 is not enough for gold, but it is at least 5, so the elif branch prints silver.", fr: "7 ne suffit pas pour gold, mais il est au moins égal à 5, donc le bloc elif affiche silver." },
  },
  {
    id: "loops-05",
    set: "easy",
    topic: "loops",
    difficulty: "easy",
    type: "output",
    prompt: { en: "What does this program print on one line?", fr: "Qu'affiche ce programme sur une seule ligne ?" },
    codeSnippet: "for number in [2, 4, 6]:\n    print(number, end=\" \" )",
    acceptedAnswers: ["2 4 6", "2 4 6 "],
    explanation: { en: "The loop visits each list item from left to right.", fr: "La boucle parcourt chaque élément de la liste de gauche à droite." },
  },
  {
    id: "loops-06",
    set: "medium",
    topic: "loops",
    difficulty: "medium",
    type: "output",
    prompt: { en: "What final value is printed?", fr: "Quelle valeur finale est affichée ?" },
    codeSnippet: "total = 0\nfor number in range(1, 5):\n    total = total + number\nprint(total)",
    acceptedAnswers: ["10"],
    explanation: { en: "range(1, 5) produces 1, 2, 3, and 4. Their sum is 10.", fr: "range(1, 5) produit 1, 2, 3 et 4. Leur somme vaut 10." },
  },
  {
    id: "loops-07",
    set: "mixed",
    topic: "loops",
    difficulty: "medium",
    type: "fill",
    prompt: { en: "What goes inside `range(___)` to produce 1, 2, 3, 4, 5? Enter only the two missing numbers.", fr: "Que faut-il écrire dans `range(___)` pour produire 1, 2, 3, 4, 5 ? Entrez seulement les deux nombres manquants." },
    acceptedAnswers: ["1, 6", "1,6"],
    explanation: { en: "Enter 1, 6. range includes 1 but stops before 6, so it produces 1 through 5.", fr: "Entrez 1, 6. range inclut 1 mais s'arrête avant 6, donc il produit les nombres de 1 à 5." },
  },
  {
    id: "loops-08",
    set: "hard",
    topic: "loops",
    difficulty: "hard",
    type: "output",
    prompt: { en: "What final number does this `while` loop print?", fr: "Quel nombre final cette boucle `while` affiche-t-elle ?" },
    codeSnippet: "number = 1\nwhile number < 10:\n    number = number * 2\nprint(number)",
    acceptedAnswers: ["16"],
    explanation: { en: "number changes from 1 to 2, 4, 8, then 16. The loop stops because 16 is not less than 10.", fr: "number passe de 1 à 2, 4, 8, puis 16. La boucle s'arrête car 16 n'est pas inférieur à 10." },
  },
  {
    id: "lists-05",
    set: "easy",
    topic: "lists",
    difficulty: "easy",
    type: "multiple-choice",
    prompt: { en: "Which index selects the first item of a Python list?", fr: "Quel indice sélectionne le premier élément d'une liste Python ?" },
    choices: ["0", "1", "-1", "first"],
    answer: "0",
    explanation: { en: "Python list indexing starts at 0.", fr: "L'indexation des listes Python commence à 0." },
  },
  {
    id: "lists-06",
    set: "medium",
    topic: "lists",
    difficulty: "medium",
    type: "output",
    prompt: { en: "What does this program print?", fr: "Qu'affiche ce programme ?" },
    codeSnippet: "numbers = [1, 2]\nnumbers.append(3)\nprint(numbers)",
    acceptedAnswers: ["[1, 2, 3]", "[1,2,3]"],
    explanation: { en: "append adds the new item to the end of the existing list.", fr: "append ajoute le nouvel élément à la fin de la liste existante." },
  },
  {
    id: "lists-07",
    set: "mixed",
    topic: "lists",
    difficulty: "medium",
    type: "output",
    prompt: { en: "What does this program print?", fr: "Qu'affiche ce programme ?" },
    codeSnippet: "letters = [\"a\", \"b\", \"c\", \"d\"]\nprint(letters[1:3])",
    acceptedAnswers: ["['b', 'c']", "[\"b\", \"c\"]", "['b','c']", "[\"b\",\"c\"]"],
    explanation: { en: "The slice starts at index 1 and stops before index 3, selecting b and c.", fr: "La tranche commence à l'indice 1 et s'arrête avant l'indice 3, sélectionnant b et c." },
  },
  {
    id: "lists-08",
    set: "hard",
    topic: "lists",
    difficulty: "hard",
    type: "output",
    prompt: { en: "What does this program print?", fr: "Qu'affiche ce programme ?" },
    codeSnippet: "scores = [4, 7, 9]\nscores[1] = 10\nscores.append(6)\nprint(scores)",
    acceptedAnswers: ["[4, 10, 9, 6]", "[4,10,9,6]"],
    explanation: { en: "Index 1 changes the second score from 7 to 10, then append adds 6 to the end.", fr: "L'indice 1 remplace le deuxième score, 7, par 10, puis append ajoute 6 à la fin." },
  },
];
